"""Stable semantic field registry for document extraction and rules.

Display labels and custom module keys may change.  These semantic keys are the
stable contract shared by extraction, review, publishing and future rule packs.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


@dataclass(frozen=True)
class SemanticField:
    key: str
    label: str
    data_type: str
    document_types: tuple[str, ...]
    unit: str | None = None
    description: str = ""
    aliases: tuple[str, ...] = ()
    rule_input: bool = False
    enum: tuple[str, ...] = ()
    required_for: tuple[str, ...] = ()
    value_shape: str = "scalar"
    field_kind: str = "fact"
    region_hints: tuple[str, ...] = ()
    validation: tuple[tuple[str, Any], ...] = ()

    def to_dict(self) -> dict[str, Any]:
        value = asdict(self)
        value["document_types"] = list(self.document_types)
        value["aliases"] = list(self.aliases)
        value["enum"] = list(self.enum)
        value["required_for"] = list(self.required_for)
        value["region_hints"] = list(self.region_hints or _region_hints(self.key))
        value["validation"] = dict(self.validation)
        return value


def _region_hints(key: str) -> tuple[str, ...]:
    prefix = key.split(".", 1)[0]
    return {
        "document": ("文件表头", "基本信息"),
        "standard": ("文件表头", "适用标准"),
        "base_material": ("母材", "基本金属"),
        "joint": ("接头", "坡口", "接头设计"),
        "welding": ("焊接方法", "焊接参数"),
        "filler": ("填充金属", "焊材"),
        "shielding": ("保护气体", "气体"),
        "electrical": ("电特性", "焊接参数"),
        "thermal": ("预热", "层间温度", "焊后热处理"),
        "ndt": ("无损检测", "检验与试验"),
        "test": ("试验结果", "检验与试验"),
        "supporting": ("支持文件", "评定依据"),
        "welder": ("焊工信息", "人员信息"),
        "certification": ("证书信息", "资格证书"),
        "qualification": ("合格项目", "资格范围"),
    }.get(prefix, ())


_FIELDS = (
    SemanticField(
        "document.title",
        "文件标题",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("标题", "文件名称", "工艺名称", "评定名称"),
        required_for=("wps", "pqr"),
        validation=(("min_length", 1), ("max_length", 200)),
    ),
    SemanticField(
        "document.number",
        "文件编号",
        "string",
        ("wps", "pqr", "ppqr"),
        description="WPS、PQR 或 pPQR 的正式编号",
        aliases=("编号", "工艺编号", "评定编号"),
        required_for=("wps", "pqr"),
        validation=(("min_length", 1), ("max_length", 50)),
    ),
    SemanticField(
        "document.revision",
        "版本",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("版次", "修订", "Revision", "Rev."),
    ),
    SemanticField(
        "document.date",
        "文件日期",
        "date",
        ("wps", "pqr", "ppqr"),
        aliases=("编制日期", "试验日期", "批准日期"),
    ),
    SemanticField(
        "standard.code",
        "适用标准",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("标准", "规范", "执行标准"),
        rule_input=True,
    ),
    SemanticField(
        "standard.version",
        "标准版本",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("标准年份", "规范版本"),
        rule_input=True,
    ),
    SemanticField(
        "base_material.specification",
        "母材牌号",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("母材", "材料牌号", "材质"),
        rule_input=True,
    ),
    SemanticField(
        "base_material.group",
        "母材组别",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("材料组别", "P-No.", "组号"),
        rule_input=True,
    ),
    SemanticField(
        "base_material.thickness",
        "母材厚度",
        "number",
        ("pqr", "ppqr"),
        unit="mm",
        aliases=("试件厚度", "板厚"),
        rule_input=True,
    ),
    SemanticField(
        "base_material.thickness_range",
        "母材厚度范围",
        "string",
        ("wps",),
        unit="mm",
        aliases=("适用厚度", "厚度范围"),
        rule_input=True,
    ),
    SemanticField(
        "base_material.diameter",
        "管径",
        "number",
        ("pqr", "ppqr"),
        unit="mm",
        aliases=("试件直径", "外径"),
        rule_input=True,
    ),
    SemanticField(
        "joint.type",
        "接头形式",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("接头类型", "接头设计"),
        rule_input=True,
    ),
    SemanticField(
        "joint.groove_type",
        "坡口形式",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("坡口类型", "坡口型式"),
        rule_input=True,
    ),
    SemanticField(
        "joint.groove_angle",
        "坡口角度",
        "number",
        ("wps", "pqr", "ppqr"),
        unit="degree",
        aliases=("夹角", "角度"),
    ),
    SemanticField(
        "joint.root_gap",
        "根部间隙",
        "number",
        ("wps", "pqr", "ppqr"),
        unit="mm",
        aliases=("根间隙", "间隙"),
    ),
    SemanticField(
        "joint.root_face",
        "钝边",
        "number",
        ("wps", "pqr", "ppqr"),
        unit="mm",
        aliases=("根部钝边",),
    ),
    SemanticField(
        "welding.process",
        "焊接方法",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("焊接工艺", "方法", "Process"),
        rule_input=True,
    ),
    SemanticField(
        "welding.position",
        "焊接位置",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("焊位", "位置"),
        rule_input=True,
    ),
    SemanticField(
        "filler.specification",
        "焊材牌号",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("填充金属", "焊丝", "焊条"),
        rule_input=True,
    ),
    SemanticField(
        "filler.classification",
        "焊材分类",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("填充金属分类",),
        rule_input=True,
    ),
    SemanticField(
        "filler.diameter",
        "焊材直径",
        "number",
        ("wps", "pqr", "ppqr"),
        unit="mm",
        aliases=("焊丝直径", "焊条直径"),
    ),
    SemanticField(
        "shielding.gas",
        "保护气体",
        "string",
        ("wps", "pqr", "ppqr"),
        aliases=("气体", "保护气体组成"),
    ),
    SemanticField(
        "electrical.current",
        "焊接电流",
        "number",
        ("pqr", "ppqr"),
        unit="A",
        aliases=("电流",),
    ),
    SemanticField(
        "electrical.voltage",
        "电弧电压",
        "number",
        ("pqr", "ppqr"),
        unit="V",
        aliases=("电压",),
    ),
    SemanticField(
        "electrical.current_range",
        "焊接电流范围",
        "string",
        ("wps",),
        unit="A",
        aliases=("电流范围", "焊接电流"),
    ),
    SemanticField(
        "electrical.voltage_range",
        "电弧电压范围",
        "string",
        ("wps",),
        unit="V",
        aliases=("电压范围", "电弧电压"),
    ),
    SemanticField(
        "welding.speed_actual",
        "实际焊接速度",
        "number",
        ("pqr", "ppqr"),
        unit="mm/min",
        aliases=("实际焊速", "行走速度"),
    ),
    SemanticField(
        "welding.speed_range",
        "焊接速度范围",
        "string",
        ("wps",),
        unit="mm/min",
        aliases=("焊速范围", "焊接速度"),
    ),
    SemanticField(
        "welding.pass_count",
        "焊道数量",
        "integer",
        ("wps", "pqr", "ppqr"),
        aliases=("焊道数",),
        validation=(("minimum", 1),),
    ),
    SemanticField(
        "welding.layer_count",
        "焊层数量",
        "integer",
        ("wps", "pqr", "ppqr"),
        aliases=("焊层数",),
        validation=(("minimum", 1),),
    ),
    SemanticField(
        "thermal.preheat_temperature",
        "预热温度",
        "number",
        ("wps", "pqr", "ppqr"),
        unit="degC",
        aliases=("最低预热温度",),
        rule_input=True,
    ),
    SemanticField(
        "thermal.interpass_temperature",
        "层间温度",
        "number",
        ("wps", "pqr", "ppqr"),
        unit="degC",
        aliases=("最高层间温度",),
        rule_input=True,
    ),
    SemanticField(
        "thermal.pwht_required",
        "是否焊后热处理",
        "boolean",
        ("wps", "pqr", "ppqr"),
        aliases=("PWHT", "焊后热处理"),
        rule_input=True,
    ),
    SemanticField(
        "thermal.pwht_temperature",
        "焊后热处理温度",
        "number",
        ("wps", "pqr", "ppqr"),
        unit="degC",
        aliases=("PWHT温度",),
        rule_input=True,
    ),
    SemanticField(
        "thermal.pwht_duration",
        "焊后热处理时间",
        "number",
        ("wps", "pqr", "ppqr"),
        unit="h",
        aliases=("保温时间", "PWHT时间"),
        rule_input=True,
    ),
    SemanticField(
        "ndt.required",
        "是否需要无损检测",
        "boolean",
        ("wps",),
        aliases=("NDE要求", "NDT要求"),
    ),
    SemanticField(
        "ndt.methods",
        "无损检测方法",
        "string",
        ("wps",),
        aliases=("NDE方法", "NDT方法", "检测方法"),
    ),
    SemanticField(
        "ndt.visual_result",
        "目视检测结果",
        "string",
        ("pqr", "ppqr"),
        aliases=("VT结果", "外观检查"),
    ),
    SemanticField(
        "ndt.rt_result",
        "射线检测结果",
        "string",
        ("pqr", "ppqr"),
        aliases=("RT结果", "射线探伤"),
    ),
    SemanticField(
        "ndt.ut_result",
        "超声检测结果",
        "string",
        ("pqr", "ppqr"),
        aliases=("UT结果", "超声探伤"),
    ),
    SemanticField(
        "ndt.mt_result",
        "磁粉检测结果",
        "string",
        ("pqr", "ppqr"),
        aliases=("MT结果", "磁粉探伤"),
    ),
    SemanticField(
        "ndt.pt_result",
        "渗透检测结果",
        "string",
        ("pqr", "ppqr"),
        aliases=("PT结果", "渗透探伤"),
    ),
    SemanticField(
        "ndt.report_number",
        "无损检测报告编号",
        "string",
        ("pqr", "ppqr"),
        aliases=("NDE报告号", "NDT报告号"),
    ),
    SemanticField(
        "test.mechanical.requirements",
        "力学性能试验要求",
        "string",
        ("wps",),
        aliases=("试验要求", "力学试验"),
    ),
    SemanticField(
        "supporting.pqr_number",
        "支持的PQR编号",
        "string",
        ("wps",),
        aliases=("PQR编号", "WPQR编号"),
        rule_input=True,
    ),
    SemanticField(
        "test.tensile.result",
        "拉伸试验结果",
        "string",
        ("pqr", "ppqr"),
        aliases=("拉伸结果",),
        rule_input=True,
    ),
    SemanticField(
        "test.tensile.strength",
        "抗拉强度",
        "number",
        ("pqr", "ppqr"),
        unit="MPa",
        aliases=("Rm", "实际抗拉强度"),
        rule_input=True,
        validation=(("minimum", 0),),
    ),
    SemanticField(
        "test.tensile.yield_strength",
        "屈服强度",
        "number",
        ("pqr", "ppqr"),
        unit="MPa",
        aliases=("ReL", "Rp0.2"),
        validation=(("minimum", 0),),
    ),
    SemanticField(
        "test.tensile.elongation",
        "延伸率",
        "number",
        ("pqr", "ppqr"),
        unit="%",
        aliases=("A%",),
        validation=(("minimum", 0), ("maximum", 100)),
    ),
    SemanticField(
        "test.bend.result",
        "弯曲试验结果",
        "string",
        ("pqr", "ppqr"),
        aliases=("弯曲结果",),
        rule_input=True,
    ),
    SemanticField(
        "test.bend.root_result",
        "根弯试验结果",
        "string",
        ("pqr", "ppqr"),
        aliases=("根弯结果", "根部弯曲"),
        rule_input=True,
    ),
    SemanticField(
        "test.bend.face_result",
        "面弯试验结果",
        "string",
        ("pqr", "ppqr"),
        aliases=("面弯结果", "表面弯曲"),
        rule_input=True,
    ),
    SemanticField(
        "test.bend.side_result",
        "侧弯试验结果",
        "string",
        ("pqr", "ppqr"),
        aliases=("侧弯结果", "侧面弯曲"),
        rule_input=True,
    ),
    SemanticField(
        "test.impact.temperature",
        "冲击试验温度",
        "number",
        ("pqr", "ppqr"),
        unit="degC",
        aliases=("冲击温度",),
        rule_input=True,
    ),
    SemanticField(
        "test.impact.energy",
        "冲击功",
        "number",
        ("pqr", "ppqr"),
        unit="J",
        aliases=("冲击吸收功",),
        rule_input=True,
    ),
    SemanticField(
        "test.impact.minimum_energy",
        "最小冲击功",
        "number",
        ("pqr", "ppqr"),
        unit="J",
        aliases=("单值最小冲击功",),
        rule_input=True,
        validation=(("minimum", 0),),
    ),
    SemanticField(
        "test.impact.performed",
        "是否进行冲击试验",
        "boolean",
        ("pqr", "ppqr"),
        aliases=("冲击试验", "Charpy试验"),
    ),
    SemanticField(
        "test.hardness.performed",
        "是否进行硬度试验",
        "boolean",
        ("pqr", "ppqr"),
        aliases=("硬度试验",),
    ),
    SemanticField(
        "test.hardness.values",
        "硬度值",
        "array",
        ("pqr", "ppqr"),
        aliases=("硬度试验",),
        rule_input=True,
        value_shape="list",
    ),
    SemanticField(
        "qualification.pqr_thickness_range",
        "PQR合格厚度范围",
        "string",
        ("pqr", "ppqr"),
        unit="mm",
        aliases=("合格厚度范围", "评定厚度范围"),
        rule_input=True,
        field_kind="derived",
    ),
    SemanticField(
        "qualification.pqr_diameter_range",
        "PQR合格直径范围",
        "string",
        ("pqr", "ppqr"),
        unit="mm",
        aliases=("合格直径范围", "评定管径范围"),
        rule_input=True,
        field_kind="derived",
    ),
    SemanticField(
        "qualification.pqr_positions",
        "PQR合格焊接位置",
        "array",
        ("pqr", "ppqr"),
        aliases=("合格位置", "评定位置"),
        rule_input=True,
        value_shape="list",
        field_kind="derived",
    ),
    SemanticField(
        "welder.code",
        "焊工编号",
        "string",
        ("welder",),
        aliases=("人员编号", "焊工代号", "Welder ID"),
        required_for=("welder",),
        validation=(("min_length", 1),),
    ),
    SemanticField(
        "welder.name",
        "焊工姓名",
        "string",
        ("welder",),
        aliases=("姓名", "持证人", "Name"),
        required_for=("welder",),
        validation=(("min_length", 1),),
    ),
    SemanticField(
        "welder.id_number",
        "身份证件号码",
        "string",
        ("welder",),
        aliases=("身份证号", "证件号码", "ID No."),
    ),
    SemanticField(
        "certification.number",
        "证书编号",
        "string",
        ("welder",),
        aliases=("资格证号", "合格证编号", "Certificate No."),
        required_for=("welder",),
    ),
    SemanticField(
        "certification.standard",
        "认证标准",
        "string",
        ("welder",),
        aliases=("考试标准", "执行标准", "Qualification Standard"),
        rule_input=True,
    ),
    SemanticField(
        "certification.issue_date",
        "发证日期",
        "date",
        ("welder",),
        aliases=("颁发日期", "Issue Date"),
    ),
    SemanticField(
        "certification.expiry_date",
        "证书有效期",
        "date",
        ("welder",),
        aliases=("到期日期", "有效期至", "Expiry Date"),
        rule_input=True,
    ),
    SemanticField(
        "qualification.items",
        "持证项目",
        "array",
        ("welder",),
        aliases=("合格项目", "资格项目", "Qualified Items"),
        rule_input=True,
        value_shape="table",
    ),
    SemanticField(
        "qualification.process",
        "合格焊接方法",
        "array",
        ("welder",),
        aliases=("焊接方法", "合格工艺"),
        rule_input=True,
        value_shape="list",
    ),
    SemanticField(
        "qualification.position",
        "合格焊接位置",
        "array",
        ("welder",),
        aliases=("焊接位置", "考试位置"),
        rule_input=True,
        value_shape="list",
    ),
    SemanticField(
        "qualification.material_group",
        "合格材料组",
        "array",
        ("welder",),
        aliases=("材料组别", "母材组别"),
        rule_input=True,
        value_shape="list",
    ),
    SemanticField(
        "qualification.thickness_range",
        "合格厚度范围",
        "string",
        ("welder",),
        unit="mm",
        aliases=("厚度范围", "适用厚度"),
        rule_input=True,
    ),
    SemanticField(
        "qualification.diameter_range",
        "合格直径范围",
        "string",
        ("welder",),
        unit="mm",
        aliases=("管径范围", "适用直径"),
        rule_input=True,
    ),
)

SEMANTIC_FIELDS = {field.key: field for field in _FIELDS}


def get_semantic_field(key: str | None) -> SemanticField | None:
    if not key:
        return None
    return SEMANTIC_FIELDS.get(key)


def list_semantic_fields(document_type: str | None = None) -> list[SemanticField]:
    values = list(SEMANTIC_FIELDS.values())
    if document_type:
        values = [field for field in values if document_type in field.document_types]
    return sorted(values, key=lambda item: item.key)
